### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hboisgon** [Deltares/HYDROLIB#79]
At least document the api part
If time document user guide

**Comment by priscavdsluis** [comment]
Copy from https://github.com/Deltares/HYDROLIB/issues/61#issuecomment-1220598305:

Hi @rhutten, I have looked again once more at the API reference documentation.
There really seems to be a problem. I constantly get errors while executing a `mkdocs serve`. I am not sure if that is because our documentation (or something else) is incorrect, or if it is a bug on mkdocs side. Eitherway, I cannot find anything about the error and I tried so many things.
 
I also tried to use the mkdocs plugin "mktheapidocs" which IS able to generate the documentation with a nice link to source code on github.

```
  - mktheapidocs:
      modules: 
        hydrolib:
          section: "API reference" 
          source_repo: https://github.com/Deltares/HYDROLIB/tree/main
          hidden: ["submodules", "to", "omit"]
```

It generates good looking html files, BUT I could not find a way to do the following: 

1. Reference the generated html files so that the user can go to these pages from the home page.
2. Use the mktheapidocs plugin within the dhydamo and the hydromt_delft3dfm mkdocs.yml -> can only use it in the root mkdocs.yml. I think this is becuase the monorepo plugin does not support this...

The mktheapidocs plugin does not have any documentation on this. So I am stuck :( maybe we can sit together sometime to figure it out.
